baseURL = "https://blev.dev/"
title = "Little Epiphanies"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true
enableGitInfo = true
enableEmoji = true
disqusShortname = "blev-dev"

[taxonomies]
  category = 'categories'
  shelf = 'shelves'

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = ['HTML', 'RSS', 'JSON']

[params]
env = "production"
title = "Little Epiphanies"
description = "I'm here to share all of the little epiphanies that shape who I am"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Benjamin Levinson"
images = [ "images/headshot.png" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false
mainSections = ["posts", "essays"]

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Benjamin Levinson is a process"
  subtitle = "I'm here to share all of the little epiphanies that shape who I am"
  imageUrl = "images/headshot.png"
  imageWidth = 300
  imageHeight = 300
  imageTitle = "Me on top of Giotto's Bell Tower in Florence, Italy"

    [[params.profileMode.buttons]]
    name = "Articles"
    url = "articles"

    [[params.profileMode.buttons]]
    name = "Slowcial media"
    url = "posts"

  [params.homeInfoParams]
  Title = "What ðŸ‘‹"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/bjlevinson"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/8167215/benjamin-l"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/benjaminLevinson"

  [[params.socialIcons]]
  name = "apple music"
  url = "https://music.apple.com/profile/benjaminlevinson"

  [[params.socialIcons]]
  name = "goodreads"
  url = "https://www.goodreads.com/user/show/45421935-benjamin-l"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/bjlevinson/"

  [[params.socialIcons]]
  name = "itchio"
  url = "https://sunrisemoon.itch.io/"

  [[params.socialIcons]]
  name = "letterboxd"
  url = "https://letterboxd.com/benjaminlevi/"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/benjamin-levinson-2b1222122/"

  [[params.socialIcons]]
  name = "ycombinator"
  url = "https://news.ycombinator.com/user?id=blev"

  # [[params.socialIcons]]
  # name = "youtube"
  # url = "https://www.youtube.com/channel/UCSKlsiJ48w10O5mSVmjzbyQ"

  [params.analytics.google]
  SiteVerificationTag = "XYZabc"

  [params.analytics.bing]
  SiteVerificationTag = "XYZabc"

  [params.analytics.yandex]
  SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/benjaminLevinson.github.io/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[markup.highlight]
noClasses = false

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
